/* Generated by cbindgen from core/bindings/src/lib.rs. Do not edit. */

#ifndef OHAND_BINDINGS_H
#define OHAND_BINDINGS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define OHAND_BINDINGS_ABI_VERSION 1

#define OHAND_STATUS_OK 0

#define OHAND_STATUS_TRANSIENT 1

#define OHAND_STATUS_PERMANENT 2

#define OHAND_STATUS_UNAUTHORIZED 3

#define OHAND_STATUS_CANCELLED 4

#define OHAND_STATUS_UNSUPPORTED 5

/**
 * Largest request (and therefore largest capture text) accepted across the boundary.
 */
#define OHAND_MAX_REQUEST_BYTES 1048576

/**
 * Opaque cooperative cancellation flag.
 */
typedef struct OhandCancelToken OhandCancelToken;

/**
 * Opaque in-memory capture store backed by the real core database.
 */
typedef struct OhandProbeStore OhandProbeStore;

/**
 * Outcome of a call. `data` points at `len` bytes owned by Rust until `ohand_result_free`.
 */
typedef struct OhandResult {
  uint32_t status;
  uint8_t *data;
  size_t len;
} OhandResult;

/**
 * Version of this C ABI; bumped on any incompatible change.
 */
uint32_t ohand_bindings_abi_version(void);

/**
 * Largest `request_len` the boundary accepts.
 */
size_t ohand_bindings_max_request_bytes(void);

/**
 * Number of live Rust-owned objects (result buffers, stores, cancel tokens). Returns to its
 * starting value when every object has been released; tests use it to prove ownership.
 */
size_t ohand_bindings_live_allocations(void);

/**
 * Opens an empty in-memory core capture store. Returns null if the store cannot be opened.
 * Release with `ohand_probe_store_free`.
 */
struct OhandProbeStore *ohand_probe_store_open_in_memory(void);

/**
 * Releases a store. Null is ignored.
 *
 * # Safety
 * `store` must be null or a pointer from `ohand_probe_store_open_in_memory` that has not
 * been freed, and no call may be using it concurrently or afterwards.
 */
void ohand_probe_store_free(struct OhandProbeStore *store);

/**
 * Creates an uncancelled token. Release with `ohand_cancel_token_free`.
 */
struct OhandCancelToken *ohand_cancel_token_new(void);

/**
 * Requests cancellation. Safe to call from any thread, repeatedly, and after the call it
 * was meant for has finished. Null is ignored.
 *
 * # Safety
 * `cancel_token` must be null or a live pointer from `ohand_cancel_token_new`.
 */
void ohand_cancel_token_cancel(const struct OhandCancelToken *cancel_token);

/**
 * Releases a token. Null is ignored.
 *
 * # Safety
 * `cancel_token` must be null or a pointer from `ohand_cancel_token_new` that has not been
 * freed, and no call may be using it concurrently or afterwards.
 */
void ohand_cancel_token_free(struct OhandCancelToken *cancel_token);

/**
 * Saves the capture described by the JSON request into the store, idempotently, and returns
 * the stored capture. `cancel_token` may be null.
 *
 * # Safety
 * `store` and `cancel_token` (if non-null) must be live handles; `request` must point at
 * `request_len` readable bytes (it may be null only when `request_len` is 0).
 */
struct OhandResult ohand_probe_save_capture(const struct OhandProbeStore *store,
                                            const struct OhandCancelToken *cancel_token,
                                            const uint8_t *request,
                                            size_t request_len);

/**
 * Returns the stored capture with the given UTF-8 identifier, or a `not_found` error.
 *
 * # Safety
 * Same requirements as `ohand_probe_save_capture`, with `capture_id` and `capture_id_len`
 * in place of `request` and `request_len`.
 */
struct OhandResult ohand_probe_get_capture(const struct OhandProbeStore *store,
                                           const struct OhandCancelToken *cancel_token,
                                           const uint8_t *capture_id,
                                           size_t capture_id_len);

/**
 * Always panics inside Rust; the call must return the `internal` failure instead of
 * unwinding into the caller. Exists only to prove panic containment.
 */
struct OhandResult ohand_probe_trigger_panic(void);

/**
 * Releases the buffer in `result` and clears it, so freeing twice is harmless. Null is
 * ignored.
 *
 * # Safety
 * `result` must be null or point at an `OhandResult` returned by this library whose buffer
 * has not been released through a copy of the struct.
 */
void ohand_result_free(struct OhandResult *result);

#endif  /* OHAND_BINDINGS_H */
