//! FFI Module - Rust-to-Swift boundary interfaces
//!
//! This module organizes the typed bindings, ABI contracts, thread safety guarantees, and error
//! conversion for the native-to-core boundary. Generated C headers are produced from the
//! bindings crate and are never committed to the repository; they are build artifacts.
//!
//! Modules declare their FFI exports locally within their `mod.rs` and register them with
//! the central bindings crate via marker types, avoiding concurrent central-file edits.
//!
//! # Module-Local Export Pattern
//!
//! To export FFI functions from a module:
//! 1. Define `#[no_mangle] pub extern "C"` functions in your module.
//! 2. Ensure the function signatures and safety contracts are documented.
//! 3. Mark them with a module-local `// EXPORTED` comment for registration.
//! 4. The cbindgen generation automatically discovers and includes them in the header.
//!
//! # Generated Bindings
//!
//! The canonical C header is generated from `core/bindings/src/lib.rs` using cbindgen.
//! Generated files:
//! - `build/ohand_bindings.h` (or target platform equivalent) — build output, not committed
//! - Generated by `tools/bindings/generate.sh` during `make check` and `make test`
//! - Verified against source via `cargo test -p ohand-bindings --test header_drift`
