//! FFI Module - Rust-to-Swift boundary interfaces
//!
//! This module organizes the typed bindings, ABI contracts, thread safety guarantees, and error
//! conversion for the native-to-core boundary. Generated C headers are produced from the
//! bindings crate and are never committed to the repository; they are build artifacts.
//!
//! # Generated Bindings
//!
//! The canonical C header is generated from the `ohand-bindings` crate using cbindgen, which
//! parses the entire crate including all modules. FFI exports are declared as `#[no_mangle] pub extern "C"`
//! functions anywhere within the crate structure; they are automatically discovered and included
//! in the generated header.
//!
//! Generated files:
//! - `build/ohand_bindings.h` (or target platform equivalent) — build output, not committed
//! - Generated by `tools/bindings/generate.sh` during `make check` and `make test`, and
//!   by `core/bindings/build-ios.sh` during iOS builds
//! - Verified against source via `cargo test -p ohand-bindings --test header_drift`
//!
//! # Module-Local Export Pattern
//!
//! Modules can declare FFI exports locally without editing the central `core/bindings/src/lib.rs`.
//! To export a C function from a submodule:
//!
//! 1. Define the function with `#[no_mangle] pub extern "C"` in the module
//! 2. The function will be automatically discovered and included in the generated header
//! 3. No central-file edits are required; later owned modules follow the same pattern
//!
//! The cbindgen generator uses crate-wide parsing (`with_crate`) to ensure all exports
//! are discovered across the entire module tree.
