//! FFI Module - Rust-to-Swift boundary interfaces
//!
//! This module organizes the typed bindings, ABI contracts, thread safety guarantees, and error
//! conversion for the native-to-core boundary. Generated C headers are produced from the
//! bindings crate and are never committed to the repository; they are build artifacts.
//!
//! # Generated Bindings
//!
//! The canonical C header is generated from `core/bindings/src/lib.rs` using cbindgen.
//! All FFI exports must be present in that file (either directly defined or re-exported from
//! other modules). cbindgen parses only that single source file.
//!
//! Generated files:
//! - `build/ohand_bindings.h` (or target platform equivalent) — build output, not committed
//! - Generated by `tools/bindings/generate.sh` during `make check` and `make test`, and
//!   by `core/bindings/build-ios.sh` during iOS builds
//! - Verified against source via `cargo test -p ohand-bindings --test header_drift`
//!
//! # Future Module-Local Export Pattern
//!
//! Planned: Modules will be able to declare FFI exports locally via a registration mechanism
//! (e.g., cbindgen discovery or a separate per-module export registry) to avoid concurrent
//! central-file edits. This is not yet implemented. For now, all exports must be added to
//! `core/bindings/src/lib.rs`.
