//! Verify that C header generation is reproducible from Rust source.
//! Headers are generated by tools/bindings/ and output to build artifacts, not committed.
//! This test verifies that cbindgen can reproduce the header deterministically and that
//! generation is identical whether performed through the generator binary or in-process.

use cbindgen::{Builder, Config};
use std::path::PathBuf;
use std::process::Command;

fn bindings_directory() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn repo_root() -> PathBuf {
    bindings_directory()
        .parent()
        .and_then(|p| p.parent())
        .expect("bindings crate is at core/bindings")
        .to_path_buf()
}

fn config_file() -> PathBuf {
    repo_root().join("tools/bindings/cbindgen.toml")
}

fn generate_header_in_process() -> String {
    let config = Config::from_file(config_file()).expect("load cbindgen.toml");
    let mut output = Vec::new();
    Builder::new()
        .with_config(config)
        .with_crate(bindings_directory())
        .generate()
        .expect("cbindgen generation with crate-wide parsing")
        .write(&mut output);
    String::from_utf8(output).expect("header is UTF-8")
}

fn generate_header_via_binary(output_dir: &PathBuf) -> String {
    let status = Command::new("cargo")
        .args([
            "run",
            "-q",
            "--manifest-path",
            "tools/bindings/Cargo.toml",
            "--",
        ])
        .arg(config_file())
        .arg(output_dir)
        .current_dir(repo_root())
        .status()
        .expect("generator binary exists and runs");
    assert!(status.success(), "generator binary failed");

    let header_path = output_dir.join("ohand_bindings.h");
    std::fs::read_to_string(&header_path).expect("generated header is readable")
}

#[test]
fn header_generation_is_reproducible() {
    let generated1 = generate_header_in_process();
    let generated2 = generate_header_in_process();
    assert_eq!(
        generated1, generated2,
        "header generation is not deterministic — in-process generation must be deterministic"
    );
}

#[test]
fn header_via_binary_matches_in_process() {
    let temp_dir = std::env::temp_dir().join(format!("ohand_bindings_test_{}", std::process::id()));
    std::fs::create_dir_all(&temp_dir).expect("create temp dir");

    let in_process = generate_header_in_process();
    let via_binary = generate_header_via_binary(&temp_dir);

    assert_eq!(
        in_process, via_binary,
        "header from generator binary must match in-process generation — they must use the same config and parsing"
    );

    std::fs::remove_dir_all(&temp_dir).expect("clean up temp dir");
}

#[test]
fn header_is_c_not_cpp_and_exports_only_the_boundary() {
    let generated = generate_header_in_process();
    for forbidden in [
        "#include <ostream>",
        "#include <new>",
        "constexpr",
        "namespace",
    ] {
        assert!(
            !generated.contains(forbidden),
            "C++ construct leaked: {forbidden}"
        );
    }
    for unrelated in [
        "DEFAULT_MAX_RESPONSE_BYTES",
        "PROFILE_SCHEMA_VERSION",
        "CORE_VERSION",
    ] {
        assert!(
            !generated.contains(unrelated),
            "unrelated core item exported: {unrelated}"
        );
    }
    assert!(generated.contains("ohand_probe_save_capture"));
    assert!(generated.contains("ohand_result_free"));
}

#[test]
fn module_local_exports_are_discovered() {
    let generated = generate_header_in_process();
    assert!(
        generated.contains("ohand_ffi_module_export_test_marker"),
        "module-local export from ffi_exports module not discovered in header — new modules must be discoverable"
    );
}
