//! The committed C header must be exactly what cbindgen generates from `src/lib.rs`.
//! Regenerate with: OHAND_UPDATE_BINDINGS_HEADER=1 cargo test -p ohand-bindings --test header_drift

use cbindgen::{Builder, Config, Language};
use std::path::PathBuf;

fn bindings_directory() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn generate_header() -> String {
    let config = Config {
        language: Language::C,
        include_guard: Some("OHAND_BINDINGS_H".to_string()),
        header: Some(
            "/* Generated by cbindgen from core/bindings/src/lib.rs. Do not edit. */".to_string(),
        ),
        usize_is_size_t: true,
        ..Config::default()
    };
    let mut output = Vec::new();
    Builder::new()
        .with_config(config)
        .with_src(bindings_directory().join("src/lib.rs"))
        .generate()
        .expect("cbindgen generation")
        .write(&mut output);
    String::from_utf8(output).expect("header is UTF-8")
}

#[test]
fn committed_header_matches_generated_header() {
    let header_path = bindings_directory().join("include/ohand_bindings.h");
    let generated = generate_header();
    if std::env::var_os("OHAND_UPDATE_BINDINGS_HEADER").is_some() {
        std::fs::write(&header_path, &generated).expect("write header");
    }
    let committed = std::fs::read_to_string(&header_path).expect("read committed header");
    assert_eq!(
        committed, generated,
        "include/ohand_bindings.h is stale; regenerate it (see this file's header comment)"
    );
}

#[test]
fn header_is_c_not_cpp_and_exports_only_the_boundary() {
    let generated = generate_header();
    for forbidden in [
        "#include <ostream>",
        "#include <new>",
        "constexpr",
        "namespace",
    ] {
        assert!(
            !generated.contains(forbidden),
            "C++ construct leaked: {forbidden}"
        );
    }
    for unrelated in [
        "DEFAULT_MAX_RESPONSE_BYTES",
        "PROFILE_SCHEMA_VERSION",
        "CORE_VERSION",
    ] {
        assert!(
            !generated.contains(unrelated),
            "unrelated core item exported: {unrelated}"
        );
    }
    assert!(generated.contains("ohand_probe_save_capture"));
    assert!(generated.contains("ohand_result_free"));
}
