//! Verify that C header generation is reproducible from Rust source.
//! Headers are generated by tools/bindings/ and output to build artifacts, not committed.
//! This test verifies that cbindgen can reproduce the header deterministically.

use cbindgen::{Builder, Config};
use std::path::PathBuf;

fn bindings_directory() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn config_file() -> PathBuf {
    bindings_directory()
        .parent()
        .and_then(|p| p.parent())
        .expect("bindings crate is at core/bindings")
        .join("tools/bindings/cbindgen.toml")
}

fn generate_header() -> String {
    let config = Config::from_file(config_file()).expect("load cbindgen.toml");
    let mut output = Vec::new();
    Builder::new()
        .with_config(config)
        .with_src(bindings_directory().join("src/lib.rs"))
        .generate()
        .expect("cbindgen generation")
        .write(&mut output);
    String::from_utf8(output).expect("header is UTF-8")
}

#[test]
fn header_generation_is_reproducible() {
    let generated1 = generate_header();
    let generated2 = generate_header();
    assert_eq!(
        generated1, generated2,
        "header generation is not deterministic — C bindings must match across all supported targets (simulator/device, architectures)"
    );
}

#[test]
fn header_is_c_not_cpp_and_exports_only_the_boundary() {
    let generated = generate_header();
    for forbidden in [
        "#include <ostream>",
        "#include <new>",
        "constexpr",
        "namespace",
    ] {
        assert!(
            !generated.contains(forbidden),
            "C++ construct leaked: {forbidden}"
        );
    }
    for unrelated in [
        "DEFAULT_MAX_RESPONSE_BYTES",
        "PROFILE_SCHEMA_VERSION",
        "CORE_VERSION",
    ] {
        assert!(
            !generated.contains(unrelated),
            "unrelated core item exported: {unrelated}"
        );
    }
    assert!(generated.contains("ohand_probe_save_capture"));
    assert!(generated.contains("ohand_result_free"));
}
